/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.infoq.telas;

import infoq.Metodos;

/**
 *
 * @author carlos
 */
public class TelaPrincipal extends javax.swing.JFrame implements Metodos{

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

     
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Deskop = new javax.swing.JPanel();
        lblfundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menCadastro = new javax.swing.JMenu();
        mencadUsuario = new javax.swing.JMenuItem();
        mencadCliente = new javax.swing.JMenuItem();
        mencadProduto = new javax.swing.JMenuItem();
        mencadVenda = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema");
        setResizable(false);
        getContentPane().setLayout(null);

        Deskop.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Deskop.setPreferredSize(new java.awt.Dimension(500, 635));
        Deskop.setLayout(new java.awt.BorderLayout());
        getContentPane().add(Deskop);
        Deskop.setBounds(0, 0, 500, 635);
        Deskop.getAccessibleContext().setAccessibleName("");

        lblfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/infoq/images/images.jpg"))); // NOI18N
        lblfundo.setMaximumSize(new java.awt.Dimension(740, 640));
        lblfundo.setMinimumSize(new java.awt.Dimension(740, 640));
        lblfundo.setPreferredSize(new java.awt.Dimension(740, 640));
        getContentPane().add(lblfundo);
        lblfundo.setBounds(0, 0, 740, 640);

        menCadastro.setText("Cadastro");

        mencadUsuario.setText("Usuario");
        mencadUsuario.setToolTipText("Usuario do sistema");
        mencadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mencadUsuarioActionPerformed(evt);
            }
        });
        menCadastro.add(mencadUsuario);

        mencadCliente.setText("Cliente");
        mencadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mencadClienteActionPerformed(evt);
            }
        });
        menCadastro.add(mencadCliente);

        mencadProduto.setText("Produtos");
        mencadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mencadProdutoActionPerformed(evt);
            }
        });
        menCadastro.add(mencadProduto);

        mencadVenda.setText("Venda");
        mencadVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mencadVendaActionPerformed(evt);
            }
        });
        menCadastro.add(mencadVenda);

        jMenuBar1.add(menCadastro);

        jMenu2.setText("ed");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(750, 686));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mencadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mencadClienteActionPerformed
        // chama a tela Cliente
        TelaCliente cliente = new TelaCliente();
        cliente.setVisible(true);
        Deskop.add(cliente);
    }//GEN-LAST:event_mencadClienteActionPerformed

    private void mencadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mencadUsuarioActionPerformed
        // chama  a tela Usuario
        TelaUsuario usuario = new TelaUsuario();
        usuario.setVisible(true);
        Deskop.add(usuario);
    }//GEN-LAST:event_mencadUsuarioActionPerformed

    private void mencadVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mencadVendaActionPerformed
        // chama a tela venda
        TelaVenda venda = new TelaVenda();
        venda.setVisible(true);
        Deskop.add(venda);
    }//GEN-LAST:event_mencadVendaActionPerformed

    private void mencadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mencadProdutoActionPerformed
        // chama a tela produto
        TelaProduto produto = new TelaProduto();
        produto.setVisible(true);
        Deskop.add(produto);
    }//GEN-LAST:event_mencadProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Deskop;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblfundo;
    private javax.swing.JMenu menCadastro;
    private javax.swing.JMenuItem mencadCliente;
    private javax.swing.JMenuItem mencadProduto;
    private javax.swing.JMenuItem mencadUsuario;
    private javax.swing.JMenuItem mencadVenda;
    // End of variables declaration//GEN-END:variables
}
