/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.infoq.telas;

/**
 *
 * @author carlos
 */
public class TelaCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaUsuario
     */
    public TelaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpCertidaoNascimento = new javax.swing.JTabbedPane();
        pCN = new javax.swing.JPanel();
        nomeCompleto = new javax.swing.JLabel();
        txtNomeCompleto = new javax.swing.JTextField();
        nomePai = new javax.swing.JLabel();
        txtNomePai = new javax.swing.JTextField();
        nomeMae = new javax.swing.JLabel();
        txtNomeMae = new javax.swing.JTextField();
        txtNomeMae1 = new javax.swing.JTextField();
        nomeMae1 = new javax.swing.JLabel();
        nomeMae2 = new javax.swing.JLabel();
        txtNomeMae2 = new javax.swing.JTextField();
        pCPF = new javax.swing.JPanel();
        nomeCompleto2 = new javax.swing.JLabel();
        txtNomeCompleto2 = new javax.swing.JTextField();
        pRG = new javax.swing.JPanel();
        nomeCompleto1 = new javax.swing.JLabel();
        txtNomeCompleto1 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Tela de Cliente");
        setPreferredSize(new java.awt.Dimension(499, 629));

        pCN.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        nomeCompleto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nomeCompleto.setText("Nome Completo:");

        nomePai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nomePai.setText("Nome Pai:");

        txtNomePai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomePaiActionPerformed(evt);
            }
        });

        nomeMae.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nomeMae.setText("Nome Mãe:");

        nomeMae1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nomeMae1.setText("Nome Mãe:");

        nomeMae2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nomeMae2.setText("Nome Mãe:");

        javax.swing.GroupLayout pCNLayout = new javax.swing.GroupLayout(pCN);
        pCN.setLayout(pCNLayout);
        pCNLayout.setHorizontalGroup(
            pCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCNLayout.createSequentialGroup()
                .addGroup(pCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pCNLayout.createSequentialGroup()
                        .addComponent(nomeMae)
                        .addGap(18, 18, 18)
                        .addComponent(txtNomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pCNLayout.createSequentialGroup()
                        .addComponent(nomePai)
                        .addGap(18, 18, 18)
                        .addComponent(txtNomePai, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pCNLayout.createSequentialGroup()
                        .addComponent(nomeCompleto)
                        .addGap(18, 18, 18)
                        .addComponent(txtNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pCNLayout.createSequentialGroup()
                        .addComponent(nomeMae1)
                        .addGap(18, 18, 18)
                        .addComponent(txtNomeMae1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pCNLayout.createSequentialGroup()
                        .addComponent(nomeMae2)
                        .addGap(18, 18, 18)
                        .addComponent(txtNomeMae2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 98, Short.MAX_VALUE))
        );
        pCNLayout.setVerticalGroup(
            pCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCNLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCompleto)
                    .addComponent(txtNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomePai)
                    .addComponent(txtNomePai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeMae)
                    .addComponent(txtNomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeMae1)
                    .addComponent(txtNomeMae1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeMae2)
                    .addComponent(txtNomeMae2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(404, Short.MAX_VALUE))
        );

        tpCertidaoNascimento.addTab("Certidão de Nascimento", pCN);

        nomeCompleto2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nomeCompleto2.setText("Nome Completo:");

        txtNomeCompleto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeCompleto2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pCPFLayout = new javax.swing.GroupLayout(pCPF);
        pCPF.setLayout(pCPFLayout);
        pCPFLayout.setHorizontalGroup(
            pCPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCPFLayout.createSequentialGroup()
                .addComponent(nomeCompleto2)
                .addGap(18, 18, 18)
                .addComponent(txtNomeCompleto2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 98, Short.MAX_VALUE))
        );
        pCPFLayout.setVerticalGroup(
            pCPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCPFLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeCompleto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeCompleto2))
                .addContainerGap(508, Short.MAX_VALUE))
        );

        tpCertidaoNascimento.addTab("Cadastro da Pessoa Fisica", pCPF);

        nomeCompleto1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nomeCompleto1.setText("Nome Completo:");

        javax.swing.GroupLayout pRGLayout = new javax.swing.GroupLayout(pRG);
        pRG.setLayout(pRGLayout);
        pRGLayout.setHorizontalGroup(
            pRGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRGLayout.createSequentialGroup()
                .addComponent(nomeCompleto1)
                .addGap(18, 18, 18)
                .addComponent(txtNomeCompleto1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 98, Short.MAX_VALUE))
        );
        pRGLayout.setVerticalGroup(
            pRGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRGLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pRGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCompleto1)
                    .addComponent(txtNomeCompleto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(508, Short.MAX_VALUE))
        );

        tpCertidaoNascimento.addTab("Carteira  de Identidade", pRG);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpCertidaoNascimento)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpCertidaoNascimento)
                .addGap(24, 24, 24))
        );

        getAccessibleContext().setAccessibleDescription("Tela de Cliente");

        setBounds(0, 0, 499, 629);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeCompleto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeCompleto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCompleto2ActionPerformed

    private void txtNomePaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomePaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomePaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nomeCompleto;
    private javax.swing.JLabel nomeCompleto1;
    private javax.swing.JLabel nomeCompleto2;
    private javax.swing.JLabel nomeMae;
    private javax.swing.JLabel nomeMae1;
    private javax.swing.JLabel nomeMae2;
    private javax.swing.JLabel nomePai;
    private javax.swing.JPanel pCN;
    private javax.swing.JPanel pCPF;
    private javax.swing.JPanel pRG;
    private javax.swing.JTabbedPane tpCertidaoNascimento;
    private javax.swing.JTextField txtNomeCompleto;
    private javax.swing.JTextField txtNomeCompleto1;
    private javax.swing.JTextField txtNomeCompleto2;
    private javax.swing.JTextField txtNomeMae;
    private javax.swing.JTextField txtNomeMae1;
    private javax.swing.JTextField txtNomeMae2;
    private javax.swing.JTextField txtNomePai;
    // End of variables declaration//GEN-END:variables
}
